//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TallyJ.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Log
    {
        public int C_RowId { get; set; }
        public System.DateTime AsOf { get; set; }
        public Nullable<System.Guid> ElectionGuid { get; set; }
        public Nullable<System.Guid> LocationGuid { get; set; }
        public string ComputerCode { get; set; }
        public string Details { get; set; }
        public string HostAndVersion { get; set; }
    }
}
