//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TallyJ.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int C_RowId { get; set; }
        public System.Guid ElectionGuid { get; set; }
        public string Title { get; set; }
        public string Details { get; set; }
        public byte[] C_RowVersion { get; set; }
        public System.DateTime AsOf { get; set; }
    }
}
