//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TallyJ.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnlineVoter
    {
        public int C_RowId { get; set; }
        public string VoterId { get; set; }
        public string VoterIdType { get; set; }
        public Nullable<System.DateTime> WhenRegistered { get; set; }
        public Nullable<System.DateTime> WhenLastLogin { get; set; }
        public string EmailCodes { get; set; }
        public string Country { get; set; }
        public string OtherInfo { get; set; }
        public string VerifyCode { get; set; }
        public Nullable<System.DateTime> VerifyCodeDate { get; set; }
        public Nullable<int> VerifyAttempts { get; set; }
        public Nullable<System.DateTime> VerifyAttemptsStart { get; set; }
    }
}
