//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TallyJ.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reason
    {
        public int C_RowId { get; set; }
        public System.Guid ReasonGuid { get; set; }
        public string ReasonGroup { get; set; }
        public string ReasonDescription { get; set; }
        public Nullable<int> SortOrder { get; set; }
    }
}
