//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TallyJ.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultTie
    {
        public int C_RowId { get; set; }
        public System.Guid ElectionGuid { get; set; }
        public int TieBreakGroup { get; set; }
        public Nullable<bool> TieBreakRequired { get; set; }
        public int NumToElect { get; set; }
        public int NumInTie { get; set; }
        public Nullable<bool> IsResolved { get; set; }
    }
}
