//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TallyJ.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SmsLog
    {
        public int C_RowId { get; set; }
        public string SmsSid { get; set; }
        public string Phone { get; set; }
        public System.DateTime SentDate { get; set; }
        public Nullable<System.Guid> ElectionGuid { get; set; }
        public Nullable<System.Guid> PersonGuid { get; set; }
        public string LastStatus { get; set; }
        public Nullable<System.DateTime> LastDate { get; set; }
        public Nullable<int> ErrorCode { get; set; }
    }
}
