//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TallyJ.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class vElectionListInfo
    {
        public int C_RowId { get; set; }
        public System.Guid ElectionGuid { get; set; }
        public string Name { get; set; }
        public Nullable<bool> ListForPublic { get; set; }
        public Nullable<System.DateTime> ListedForPublicAsOf { get; set; }
        public string ElectionPasscode { get; set; }
        public Nullable<System.DateTime> DateOfElection { get; set; }
        public string ElectionType { get; set; }
        public string ElectionMode { get; set; }
        public Nullable<bool> ShowAsTest { get; set; }
        public Nullable<int> NumVoters { get; set; }
    }
}
