//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TallyJ.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voter
    {
        public int C_RowId { get; set; }
        public System.Guid ElectionGuid { get; set; }
        public System.Guid PersonGuid { get; set; }
        public Nullable<bool> CanVote { get; set; }
        public Nullable<bool> CanReceiveVotes { get; set; }
        public Nullable<System.Guid> IneligibleReasonGuid { get; set; }
        public Nullable<System.DateTime> RegistrationTime { get; set; }
        public Nullable<System.Guid> VotingLocationGuid { get; set; }
        public string VotingMethod { get; set; }
        public Nullable<int> EnvNum { get; set; }
        public string Teller1 { get; set; }
        public string Teller2 { get; set; }
        public string RegLog { get; set; }
        public Nullable<bool> HasOnlineBallot { get; set; }
        public string KioskCode { get; set; }
        public string Flags { get; set; }
        public byte[] C_RowVersion { get; set; }
        public Nullable<long> C_RowVersionInt { get; set; }
    }
}
