// <auto-generated />
namespace TallyJ.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Newcolumns : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Newcolumns));
        
        string IMigrationMetadata.Id
        {
            get { return "201304201642587_New columns"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
