// <auto-generated />
namespace TallyJ.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Removedview : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Removedview));
        
        string IMigrationMetadata.Id
        {
            get { return "201304160649341_Removed view"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
