// <auto-generated />
namespace TallyJ.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Removeinvalidreasonforblankvote : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Removeinvalidreasonforblankvote));
        
        string IMigrationMetadata.Id
        {
            get { return "201304160804346_Remove invalid reason for blank vote"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
